os: osx
osx_image: xcode8.3

language: node_js
node_js: 8

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version v0.27.5
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  # - yarn test
  - yarn release

branches:
  only:
    - master
